config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  resources :picture_comments
  resources :stories do
    resources :story_comments
  end
  resources :pictures do
    resources :picture_comments
  end
  # resources :comments

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :destroy]

  get '/', to: "home#index"
  get 'search', to: "home#search"
  root to: 'home#index'

  get('/about', {to: 'home#show'})

  get('/donation', {to: 'home#donation'})

  resources :comments

  resources :video_comments

  resources :posts do
    resources :comments
  end
  # root to: 'videos#index'
  resources :videos do
    resources :video_comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :dashboard
  end
  
end

app/models/video.rb
class Video < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :description]
    pg_search_scope :search, against: [:title, :description]
    has_one_attached :clip
    belongs_to :user
    has_one_attached :thumbnail
    has_many :video_comments, dependent: :destroy
    validates(:view_count, numericality: {
        greater_than_or_equal_to: 0
    })
    before_validation :set_default_view_count
    private
    def set_default_view_count
        self.view_count ||= 0
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  VIDEOS_PER_PAGE = 3
  # GET /videos
  # GET /videos.json
  def index
    @videosperpage = VIDEOS_PER_PAGE
    if params.fetch(:page, 0).to_i < 0
      @page = 0
    else
      @page = params.fetch(:page, 0).to_i
    end
      @allvideos = Video.all.count.to_i
      @videos = Video.offset(@page * VIDEOS_PER_PAGE).limit(VIDEOS_PER_PAGE)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video_comments = @video.video_comments.all.order(created_at: :desc)
    @video_comment = VideoComment.new
    @video.view_count += 1
    @video.save

  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :clip, :thumbnail)
    end
    def authorize_user!
      unless can?(:manage, @video)
        flash[:danger] = "Access Denied"
        redirect_to video_path(@video)
      end
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="container">
<div style="width: 80%; margin: 0 auto;">

<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :clip %>
    <%= form.file_field :clip, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit "Submit Video", class: "btn btn-lg btn-primary btn-default", style: "color:white;"%>
  </div>
<% end %>

</div>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<div class="">
  <%= link_to 'Submit A Video', new_video_path, class: "btn btn-lg btn-primary" %>
</div>
<br>



<% unless @page == 0 %>
<%= link_to "First Page", videos_path(page: 0) %>
|
<%= link_to "Previous Page", videos_path(page: @page - 1) %>
|
<% end %>



<% unless (@page + 1) > (@allvideos / @videosperpage) %>
<% unless ((@page + 1) * @videosperpage) == @allvideos %>
  <%= link_to "Next Page", videos_path(page: @page + 1) %>
  |
    <% if (@allvideos % @videosperpage) == 0 %>
    |
      <%= link_to "Last Page", videos_path(page: ((@allvideos / @videosperpage)-1)) %>
    <% else %>
    |
      <%= link_to "Last Page", videos_path(page: ((@allvideos / @videosperpage))) %>
    <% end %>
<% end %>
<% end %>










<div class="row text-center" style="display:flex; flex-wrap: wrap;">
  <% @videos.each do |video| %>
    <div class="col-lg-4 col-md-3 col-sm-2">
    <div class="">
        <%= link_to image_tag(video.thumbnail, class: "img-thumbnail thumbnail img-fluid"), video %>
        </div>
        <%= video.title %><br>
        <small>Posted by <%= video.user&.full_name || "[DELETED]" %></small>
    </div>
  <% end %>
</div>

<% if false %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <% if user_signed_in? && can?(:manage, video) %>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><small>Posted by <%= video.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>
<% if false %>
<div style="width:400px; height:400px">
<%= image_tag(@video.thumbnail, style:'width:100%;height:auto') %>
</div>
<% end %>
<div style="width:80%; height:80%;">
<%= video_tag(url_for(@video.clip), style:'width:100%;height:auto', controls: '') %>
</div>
<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <small>Seen <%= @video.view_count %> time(s) </small>
  <small>Posted by <%= @video.user&.full_name || "[DELETED]" %></small>
</p>
<% if user_signed_in? && can?(:manage, @video)%>
<%= link_to 'Edit Video Submission', edit_video_path(@video) %> |
<%= link_to 'Destroy', @video, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back to Video Index', videos_path(:page => "0") %>

<h2>Comments</h2>
<%= form_for [@video, @video_comment] do |f| %>
  <%#= f.hidden_field :video_id, value: @video.id %>
  <div>
    <%= f.text_area(
      :body, cols: 60, rows: 6,
      placeholder: "Tell us what you think of this video!"
    ) %>
  </div>
  <%= f.submit "Submit Video Comment" %>
<% end %>

<div>
  <% @video_comments.each do |comment| %>
    <div>
      <p>
        <%= comment.body %> <br />
        <small>
          Posted <%= time_ago_in_words(comment.created_at) %> ago
        </small>
      </p>
      <% if user_signed_in? && can?(:manage, comment) %>
      <small><%= link_to("Delete Video Comment", video_video_comment_path(@video,comment),method: :delete, data: { confirm: "Are you sure?"}) %></small>
      <small><%= link_to("Edit Video Comment", edit_video_comment_path(comment)) %></small>
      <% end %>
      <small>Posted by <%= comment.user&.full_name || "[DELETED]" %></small>
    </div>
  <% end %>
</div>