config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  resources :picture_comments
  resources :stories do
    resources :story_comments
  end
  resources :pictures do
    resources :picture_comments
  end
  # resources :comments

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :destroy]

  get '/', to: "home#index"
  get 'search', to: "home#search"
  root to: 'home#index'

  get('/about', {to: 'home#show'})

  get('/donation', {to: 'home#donation'})

  resources :comments

  resources :video_comments

  resources :posts do
    resources :comments
  end
  # root to: 'videos#index'
  resources :videos do
    resources :video_comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :dashboard
  end
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can(:manage, Comment) do |comment|
      user == comment.user
    end
    can(:manage, Picture) do |picture|
      user == picture.user
    end
    can(:manage, Post) do |post|
      user == post.user
    end
    can(:manage, Story) do |story|
      user == story.user
    end
    can(:manage, VideoComment) do |video_comment|
      user == video_comment.user
    end
    can(:manage, Video) do |video|
      user == video.user
    end
    can(:manage, PictureComment) do |picture_comment|
      user == picture_comment.user
    end
    can(:manage, StoryComment) do |story_comment|
      user == story_comment.user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:body]
  pg_search_scope :search, against: [:body]
  belongs_to :post
  validates :body, presence: true
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :description]
    pg_search_scope :search, against: [:title, :description]
    has_one_attached :picture
    has_many :picture_comments, dependent: :destroy
    belongs_to :user
end

app/models/picture_comment.rb
class PictureComment < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:body]
  pg_search_scope :search, against: [:body]
  belongs_to :picture
  validates :body, presence: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :body]
    pg_search_scope :search, against: [:title, :body]

    validates(:title, presence: true)

    belongs_to :user

    has_many :comments, dependent: :destroy

    validates(
        :body,
        presence: {
            message: "Message body must be present."
        },
        length: {
            minimum: 10,
            maximum: 5000
        }
    )

    validates(
        :view_count,
        numericality: {
            greater_than_or_equal_to: 0
        }
    )

    validates(
        :like_count,
        numericality: {
            greater_than_or_equal_to: 0
        }
    )

    before_validation :set_default_like_count
    before_validation :set_default_view_count

    private 

    def set_default_view_count
        self.view_count ||= 0
    end 

    def set_default_like_count
        self.like_count ||= 0
    end 

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :video_comment
  validates :body, presence: true
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :body]
    pg_search_scope :search, against: [:title, :body]
    validates(:title, presence: true)
    validates(:body, presence: {message: "Must be present!"}, length: {minimum: 10})
    validates(:view_count, numericality: {greater_than_or_equal_to: 0})
    has_many :story_comments, dependent: :destroy
    belongs_to :user
    before_validation :set_default_view_count
    private
    def set_default_view_count
        self.view_count ||= 0
    end
end

app/models/story_comment.rb
class StoryComment < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:body]
  pg_search_scope :search, against: [:body]
  belongs_to :story
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates(:email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX)
    has_many :comments, dependent: :nullify
    has_many :pictures, dependent: :nullify
    has_many :posts, dependent: :nullify
    has_many :replies, dependent: :nullify
    has_many :stories, dependent: :nullify
    has_many :video_comments, dependent: :nullify
    has_many :videos, dependent: :nullify
    has_many :picture_comments, dependent: :nullify
    has_many :story_comments, dependent: :nullify
    def full_name
        name
    end
end

app/models/video.rb
class Video < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :description]
    pg_search_scope :search, against: [:title, :description]
    has_one_attached :clip
    belongs_to :user
    has_one_attached :thumbnail
    has_many :video_comments, dependent: :destroy
    validates(:view_count, numericality: {
        greater_than_or_equal_to: 0
    })
    before_validation :set_default_view_count
    private
    def set_default_view_count
        self.view_count ||= 0
    end
end

app/models/video_comment.rb
class VideoComment < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:body]
  pg_search_scope :search, against: [:body]
  belongs_to :video
  validates :body, presence: true
  has_many :replies, dependent: :destroy
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController    
    def index
        @videos = Video.last(3)
        @posts = Post.last(10)
        @pictures = Picture.last(3)
    end
    def show
    end
    def donation
    end
    def search 
        if params[:q].blank? 
            redirect_to(root_path, alert: "No Search Query Given!") and return
        else 
            parameter = params[:q].downcase
            @posts = Post.search(params[:q]).limit(10)
            @stories = Story.search(params[:q]).limit(10)
            @videos = Video.search(params[:q]).limit(10)
            @pictures = Picture.search(params[:q]).limit(10)
        end
    end 
    private 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/donation.html.erb
<h1> Donations and Funding </h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</p>

<p>- Forrest Wong</p>

<hr>

<p>Bitcoin Address:<p> 

<%= image_tag("qrcode.png") %>

<p>36CDyWtok6Pwc1hXEHSsDxcBkJFpsFgoNg<p>

app/views/home/index.html.erb
<!-- News jumbotron -->
<div class="jumbotron text-center hoverable p-4">

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-md-4 offset-md-1 mx-3 my-3">

      <!-- Featured image -->
      <div class="view overlay">
        <%= image_tag("codecore.jpg", class: "img-fluid") %>

        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-md-7 text-md-left ml-3 mt-3">

      <!-- Excerpt -->
      <% if false %>
      <a href="#!" class="green-text">
        <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i> Work</h6>
      </a>
      <% end %>

      <h4 class="h4 mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</h4>

      <p class="font-weight-normal">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</p>
      <p class="font-weight-normal"><a><strong>Forrest Wong</strong></a></p>

      <%= link_to 'Read More', about_path, class: "btn btn-success" %>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</div>
<!-- News jumbotron -->


<p id="notice"><%= notice %></p>

<h1>Latest Videos</h1>
<h5><%= link_to 'New Video', new_video_path %></h5>

<div class="row text-center" style="display:flex; flex-wrap: wrap;">
  <% @videos.each do |video| %>
    <div class="col-lg-4 col-md-3 col-sm-2">
    <div class="">
        <%= link_to image_tag(video.thumbnail, class: "img-thumbnail thumbnail img-fluid"), video %>
        </div>
        <%= video.title %><br>
        <small>Posted by <%= video.user&.full_name || "[DELETED]" %></small>
    </div>
  <% end %>
</div>

<% if false %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td>
        <div style="width:400px; height:400px; float: left;">
<%= video_tag(url_for(video.clip), style:'width:100%;height:auto', controls: '') %>
</div>
<small>Posted by <%= video.user&.full_name || "[DELETED]" %></small>
</td>
        <td><%= link_to 'Show', video %></td>
        <% if user_signed_in? && can?(:manage, video)%>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>



<hr> 

<h1>Latest Pictures</h1>
<h5><%= link_to 'New Picture', new_picture_path %></h5>

<div class="row text-center" style="display:flex; flex-wrap: wrap;">
  <% @pictures.each do |picture| %>
    <div class="col-lg-4 col-md-3 col-sm-2">
    <div class="">
        <%= link_to image_tag(picture.picture, class: "img-thumbnail thumbnail img-fluid"), picture %>
        </div>
        <%= picture.title %><br>
        <small>Posted by <%= picture.user&.full_name || "[DELETED]" %></small>
    </div>
  <% end %>
</div>

<% if false %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td style="width:400px; height:400px;"><%= image_tag(picture.picture, style:'width:100%;height:auto') %>
        <small>Posted by <%= picture.user&.full_name || "[DELETED]" %></small>
        </td>
        <td><%= link_to 'Show', picture %></td>
        <% if user_signed_in? && can?(:manage, picture)%>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>



<hr>

<h1>Latest Forum Posts</h1>
<h5><%= link_to 'New Post', new_post_path %></h5>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post, {:style=> 'color:white;'} %></td>
        <td><%= post.body %></td>
        <% if false %>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? && can?(:manage, post)%>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
        <td><small>Posted by <%= post.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/home/search.html.erb
<h1>Search Results</h1>

<h2> Forum Posts </h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="title"><%= link_to post.title, post %></td>
        <td class="body"><%= post.body %></td>
        <% if false %>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? && can?(:manage, post) %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
        <td><small>Posted by <%= post.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2> Stories </h2>

<table class="container">
  <thead>
    <tr class="row">
      <th class="col-4">Title</th>
      <th class="col-4">Snippet</th>
      <th class="col-1"></th>
      <th class="col-1"></th>
      <th class="col-1"></th>
      <th class="col-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr class="row">
        <td class="col-4 title"><%= link_to story.title, story %></td>
        <td class="col-4 body"><%= story.body %></td>
        <% if false %>
        <td class="col-1"><%= link_to 'Show', story %></td>
        <% if user_signed_in? && can?(:manage, story) %>
        <td class="col-1"><%= link_to 'Edit', edit_story_path(story) %></td>
        <td class="col-1"><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
        <td class="col-1"><small>Posted by <%= story.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2> Videos </h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <% if user_signed_in? && can?(:manage, video) %>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><small>Posted by <%= video.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2> Pictures </h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><%= image_tag(picture.picture) %></td>
        <td><%= link_to 'Show', picture %></td>
        <% if user_signed_in? && can?(:manage, picture) %>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><small>Posted by <%= picture.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/show.html.erb
<style>
    aside {
        display: none;
    }
</style>

<h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</h1>

<br>
<br>

<main>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh.</p>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet augue interdum risus lobortis, non hendrerit ex scelerisque. Proin dapibus efficitur ullamcorper. Nam nec dolor quis justo venenatis hendrerit a quis ligula. Suspendisse facilisis, felis sed molestie posuere, orci nulla fermentum nulla, egestas ultricies ex nisl sed nibh. 
</p>

<br>
<p>- Forrest Wong</p>

<div>
    <h3>Admin Profiles</h3>

    <button data-page="page1">Harry</button>
    <button data-page="page2">Hermione</button>
    <button data-page="page3">Ron</button>

    <aside id="page1">
        <h2>Harry Potter</h2>
        <img src="https://media1.popsugar-assets.com/files/thumbor/fAzDfg5bOasPxyoo9A4CPbgvxWw/660x0:1312x967/fit-in/728xorig/filters:format_auto-!!-:strip_icc-!!-/2020/02/28/913/n/1922283/d41abaac5e597e33a9d771.12680042_/i/Harry-Potter-Quotes-Quiz.jpg" width="400" />
        <p>Harry had a thin face, knobbly knees, black hair and bright-green eyes. He wore round glasses held together with a lot of Sellotape because of all the times Dudley had punched him on the nose.</p>
    </aside>
    <aside id="page2">
        <h2>Hermione Granger</h2>
        <img src="https://myhero.com/images/guest/g282317/hero105677/image2.jpg" width="400" />
        <p>Hermione first met Harry Potter and Ron Weasley aboard the Hogwarts Express, who found her unfriendly and somewhat of an "insufferable know-it-all", an impression reinforced by her constant correct answers and eagerness to please the professors. However, she stepped in to take the blame from the boys after they had saved her from a troll on Hallowe'en in 1991, surprising them in a grateful way, which led to them quickly becoming friends. She later played a crucial role in protecting the Philosopher's Stone from Voldemort.</p>
    </aside>
    <aside id="page3">
        <h2>Ron Weasley</h2>
        <img src="https://upload.wikimedia.org/wikipedia/en/5/5e/Ron_Weasley_poster.jpg" width="400" />
        <p>He skipped his last year of school in order to accompany Harry and Hermione on a hunt to destroy all of Lord Voldemort's Horcruxes and fought in the Battle of Hogwarts in 1998, during which he lost his brother Fred, a loss which devastated him and his family, especially George, Fred's twin.</p>
    </aside>
</div>

</main>

<script>

function showPage(page) {

    document.querySelectorAll('aside').forEach(p => {
        p.style.display = "none";
    });

    document.getElementById(page).style.display = "block";

}


document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll("button").forEach(button => {
        button.onclick = function() {
            showPage(this.dataset.page);
        };
    });
});

</script>