config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  resources :picture_comments
  resources :stories do
    resources :story_comments
  end
  resources :pictures do
    resources :picture_comments
  end
  # resources :comments

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :destroy]

  get '/', to: "home#index"
  get 'search', to: "home#search"
  root to: 'home#index'

  get('/about', {to: 'home#show'})

  get('/donation', {to: 'home#donation'})

  resources :comments

  resources :video_comments

  resources :posts do
    resources :comments
  end
  # root to: 'videos#index'
  resources :videos do
    resources :video_comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :dashboard
  end
  
end

app/models/story.rb
class Story < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :body]
    pg_search_scope :search, against: [:title, :body]
    validates(:title, presence: true)
    validates(:body, presence: {message: "Must be present!"}, length: {minimum: 10})
    validates(:view_count, numericality: {greater_than_or_equal_to: 0})
    has_many :story_comments, dependent: :destroy
    belongs_to :user
    before_validation :set_default_view_count
    private
    def set_default_view_count
        self.view_count ||= 0
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  STORIES_PER_PAGE = 20
  # GET /stories
  # GET /stories.json
  def index
    @storiesperpage = STORIES_PER_PAGE
    if params.fetch(:page, 0).to_i < 0
      @page = 0
    else
      @page = params.fetch(:page, 0).to_i
    end
      @allstories = Story.all.count.to_i
      @stories = Story.offset(@page * STORIES_PER_PAGE).limit(STORIES_PER_PAGE)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story_comment = StoryComment.new
    @story_comments = @story.story_comments.order(created_at: :desc)
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = current_user
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :body)
    end
    def authorize_user!
      unless can?(:manage, @story)
        flash[:danger] = "Access Denied"
        redirect_to story_path(@story)
      end
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<div class="container">
<div style="width: 80%; margin: 0 auto;">
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit "Submit Story", class: "btn btn-lg btn-primary btn-default", style: "color:white;" %>
  </div>
<% end %>
</div>
</div>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>
<div>
<%= link_to 'Submit A Story', new_story_path, class: "btn btn-lg btn-primary" %>
</div>
<br>




<% unless @page == 0 %>
<%= link_to "First Page", stories_path(page: 0) %>
|
<%= link_to "Previous Page", stories_path(page: @page - 1) %>
|
<% end %>



<% unless (@page + 1) > (@allstories / @storiesperpage) %>
<% unless ((@page + 1) * @storiesperpage) == @allstories %>
  <%= link_to "Next Page", stories_path(page: @page + 1) %>
  |
      <% if (@allstories % @storiesperpage) == 0 %>
      
        <%= link_to "Last Page", stories_path(page: ((@allstories / @storiesperpage)-1)) %>
      <% else %>
      
        <%= link_to "Last Page", stories_path(page: ((@allstories / @storiesperpage))) %>
      <% end %>
<% end %>
<% end %>







<table class="container">
  <thead>
    <tr class="row">
      <th class="col-4">Title</th>
      <th class="col-4">Snippet</th>
      <th class="col-1"></th>
      <th class="col-1"></th>
      <th class="col-1"></th>
      <th class="col-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr class="row">
        <td class="col-4 title"><%= link_to story.title, story %></td>
        <td class="col-4 body"><%= story.body %></td>
        <% if false %>
        <td class="col-1"><%= link_to 'Show', story %></td>
        <% if user_signed_in? && can?(:manage, story) %>
        <td class="col-1"><%= link_to 'Edit', edit_story_path(story) %></td>
        <td class="col-1"><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
        <td class="col-1"><small>Posted by <%= story.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<script type="text/javascript">
window.onload = function() {
    let title = document.getElementsByClassName("title");
      for (let i = 0; i < title.length; i++) {
        if (title[i].innerHTML.length > 100) {
          title[i].innerHTML = title[i].innerHTML.slice(0,100)+"..."
        } 
      }
      let body = document.getElementsByClassName("body");
      for (let i = 0; i < body.length; i++) {
        if (body[i].innerHTML.length > 50) {
          body[i].innerHTML = body[i].innerHTML.slice(0,50)+"..."
        } 
      }
}
</script>

app/views/stories/new.html.erb
<h1>Post a New Story</h1>

<%= render 'form', story: @story %>
<br>
<%= link_to 'Back to Stories Index', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @story.body %>
</p>
<% if user_signed_in? && can?(:manage, @story) %>
<%= link_to 'Delete', @story, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_story_path(@story) %> |
<% end %>
<%= link_to 'Back', stories_path(:page => "0")  %>
<small>Posted by <%= @story.user&.full_name || "[DELETED]" %></small>

<h2>Comments</h2>

<%= form_for [@story, @story_comment] do |f| %>
  <%#= f.hidden_field :story_id, value: @story.id %>
  <div>
    <%= f.text_area(
      :body, cols: 60, rows: 6, placeholder: "What did you think of this story?"
    ) %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

<div class="answer-list">
  <% @story_comments.each do |comment| %>
      <div>
        <p>
          <%= comment.body %> <br />
          <small>
            Posted <%= time_ago_in_words(comment.created_at) %> ago
          </small>
          <% if user_signed_in? && can?(:manage, comment) %>
          <small><%= link_to("Delete Comment", story_comment_path(comment),method: :delete, data: { confirm: "Are you sure?"}) %></small>
          <small><%= link_to("Edit Comment", edit_story_comment_path(comment)) %></small>
          <% end %>
          <small>Posted by <%= comment.user&.full_name || "[DELETED]" %></small>
        </p>
      </div>
    <% end %>
</div>