config/routes.rb
Rails.application.routes.draw do
  resources :story_comments
  resources :picture_comments
  resources :stories do
    resources :story_comments
  end
  resources :pictures do
    resources :picture_comments
  end
  # resources :comments

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :destroy]

  get '/', to: "home#index"
  get 'search', to: "home#search"
  root to: 'home#index'

  get('/about', {to: 'home#show'})

  get('/donation', {to: 'home#donation'})

  resources :comments

  resources :video_comments

  resources :posts do
    resources :comments
  end
  # root to: 'videos#index'
  resources :videos do
    resources :video_comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :dashboard
  end
  
end

app/models/picture.rb
class Picture < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :description]
    pg_search_scope :search, against: [:title, :description]
    has_one_attached :picture
    has_many :picture_comments, dependent: :destroy
    belongs_to :user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  PICTURES_PER_PAGE = 3
  # GET /pictures
  # GET /pictures.json
  def index
    @picturesperpage = PICTURES_PER_PAGE
    if params.fetch(:page, 0).to_i < 0
      @page = 0
    else
      @page = params.fetch(:page, 0).to_i
    end
      @allpictures = Picture.all.count.to_i
      @pictures = Picture.offset(@page * PICTURES_PER_PAGE).limit(PICTURES_PER_PAGE)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture_comments = @picture.picture_comments.order(created_at: :desc)
    @picture_comment = PictureComment.new
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user
    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:title, :description, :picture)
    end
    def authorize_user!
      unless can?(:manage, @picture)
        flash[:danger] = "Access Denied"
        redirect_to picture_path(@picture)
      end
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="container">
<div style="width: 80%; margin: 0 auto;">

<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit "Submit Picture", class: "btn btn-lg btn-primary btn-default", style: "color:white;" %>
  </div>
<% end %>

</div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>
<div>
<%= link_to 'Submit A Picture', new_picture_path, class: "btn btn-lg btn-primary" %>
</div>
<br>


<% unless @page == 0 %>
<%= link_to "First Page", pictures_path(page: 0) %>
|
<%= link_to "Previous Page", pictures_path(page: @page - 1) %>
<% end %>


<% unless (@page + 1) > (@allpictures / @picturesperpage) %>
<% unless ((@page + 1) * @picturesperpage) == @allpictures %>
  |
  <%= link_to "Next Page", pictures_path(page: @page + 1) %>
      <% if (@allpictures % @picturesperpage) == 0 %>
      |
        <%= link_to "Last Page", pictures_path(page: ((@allpictures / @picturesperpage)-1)) %>
      <% else %>
      |
        <%= link_to "Last Page", pictures_path(page: ((@allpictures / @picturesperpage))) %>
      <% end %>
  <% end %>
<% end %>



<div class="row text-center" style="display:flex; flex-wrap: wrap;">
  <% @pictures.each do |picture| %>
    <div class="col-lg-4 col-md-3 col-sm-2">
    <div class="">
        <%= link_to image_tag(picture.picture, class: "img-thumbnail thumbnail img-fluid"), picture %>
        </div>
        <div class="caption">
          <%= picture.title %><br>
          <small>Posted by <%= picture.user&.full_name || "[DELETED]" %></small>
        </div>
    </div>
  <% end %>
</div>

<% if false %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><%= image_tag(picture.picture) %></td>
        <td><%= link_to 'Show', picture %></td>
        <% if user_signed_in? && can?(:manage, picture) %>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><small>Posted by <%= picture.user&.full_name || "[DELETED]" %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <%= image_tag(@picture.picture) %>
</p>

<small>Posted by <%= @picture.user&.full_name || "[DELETED]" %></small>
<% if user_signed_in? && can?(:manage, @picture)%>
<%= link_to 'Destroy', @picture, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<% end %>
<%= link_to 'Back', pictures_path(:page => "0") %>

<h2>Comments</h2>

<%= form_for [@picture, @picture_comment] do |f| %>
  <%#= f.hidden_field :picture_id, value: @picture.id %>
    <div>
      <%= f.text_area(:body, cols: 60, rows: 6, placeholder: "How do you like this picture?") %>
    </div>
  <%= f.submit "Submit" %>
<% end %>

<div class="answer-list">
  <% @picture_comments.each do |comment| %>
    <div>
      <p>
        <%= comment.body %> <br />
        <small>
          Post <%= time_ago_in_words(comment.created_at) %> ago
        </small>
        <small>Posted by <%= comment.user&.full_name || "[DELETED]" %></small>
      </p>
      <% if user_signed_in? && can?(:manage, comment)%>
      <small><%= link_to("Delete Comment", picture_comment_path(comment),method: :delete, data: { confirm: "Are you sure?"}) %></small>
      <small><%= link_to("Edit Comment", edit_picture_comment_path(comment)) %></small>
      <% end %>
    </div>
  <% end %>
</div>